[package]
name = "client-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
sql-manager = { workspace = true }
env-config = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
webdav-client = { workspace = true }